# arxivの学問領域の指定
subject: 'astro-ph'

# 検索キーワード
keywords:
        envelope: 2
        infall: 2
        model: 1
        protoplanetary discs: 3
        protostar: 2
        protostars: 2
        ALMA : 2
        Class 0: 2
        
        

# 通知の閾値
score_threshold: 3
