# arxivの学問領域の指定
subject: 'astro-ph'

# 検索キーワード
keywords:
        envelope: 2
        infall: 2
        model: 1
        star formation: 2
        starformation: 2
        protoplanetary discs: 2
        protostar: 2
        protostars: 2
        ALMA : 3
        Class 0: 2
        
        

# 通知の閾値
score_threshold: 3
